baseURL = 'https://wattwise.games/'
languageCode = 'en-us'
title = 'Watt-Wise Game Jam'
theme = 'wattwise'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    ordered = false
    startLevel = 2
    endLevel = 3


